export const useWorkStore = definePiniaStore("work-store", {
  state: () => ({
    work: [
      {
        id: 1,
        title: "WALK THAT TALK",
        headerImage: "/images/work/project-thumbnails/wtt.jpg",
        headerImageAlt: "WTT",
        client: "WALK THAT TALK",
        date: "2024 - NOW",
        tags: ["Logo Design","Brand Identity", "Merch Design"],
        description:
          "Walk That Talk is a cultural institution inspired by the underground culture. Connecting communities with audiences through different forms of expression. Through events, stories, art, workshops, markets, and cultural activities. \n\n Focus on the identity was creating a loud and clear tone of voice that was playful at the same time. 'Walk That Talk' is an expression like an order within the army. The morse code serves as a universal language with a clear purpose, much like art within underground culture. Both communicate meaning beyond words, serving as tools of connection and expression.",
        images: [
          "/images/work/wtt/logo.jpg",
          "/images/work/wtt/weestep.jpg",
          "/images/work/wtt/colors.jpg",
          "/images/work/wtt/Weestep-jumpdown.gif",
          "/images/work/wtt/Weestep-run2.gif",
          "/images/work/wtt/brandguide.jpg",
          "/images/work/wtt/camoprint.jpg",
          "/images/work/wtt/faces.jpg",
          "/images/work/wtt/wtt-scarves.jpg",
          "/images/work/wtt/wtt-bandanas.jpg",
          "/images/work/wtt/wtt-tees.jpg",
        ],
        mobileLayout:"1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr/ 1fr / 1fr / 1fr",
        desktopLayout: "1fr / 1fr / 1fr / 1fr 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr",
      },
      {
        id: 1,
        title: "TNO Messenger Capsule Collection teaser",
        headerImage: "/images/work/project-thumbnails/msn-tno.jpg",
        headerImageAlt: "HD24-teaser",
        client: "The New Originals",
        date: "2024",
        tags: ["Campaign Graphics", "Motion Design", "Illustration"],
        description:
          " For The New Originals holiday drop, the capsule collection explores the nostalgic era of internet within the theme of MSN Messenger. The collection consist of graphical jerseys, hoodies and a cap catered to this theme. As part of the drop, a teaser rolled out to announce the collection. \n\n The concept initially started as a loading animation of the messenger dolls, developed into a full storytelling exploring the theme of MSN. Assets were developed with multiple softwares: Figma, Procreate and After Effects). \n\n Collaborators: Eben Badu, special credits to Gabriel Polo for developing the capsule collection. ",
        images: [
          ["/images/work/tno-msn/msn-teaser-final.webm",
            "/images/work/tno-msn/start.png",
            "/images/work/tno-msn/msn-teaser-final.mp4",
          ],
          "/images/work/tno-msn/start.png",
          "/images/work/tno-msn/loading-dolls.gif",
          "/images/work/tno-msn/contacts.png",
          "/images/work/tno-msn/chat.png",
          "/images/work/tno-msn/sentFile.png",
        ],
        mobileLayout:"1fr / 1fr / 1fr / 1fr / 1fr / 1fr",
        desktopLayout: "1fr / 1fr / 1fr 1fr / 1fr / 1fr / 1fr / 1fr / 1fr",
      },    
      {
        id: 1,
        title: "SMIB X TNO FEST '24",
        headerImage: "/images/work/project-thumbnails/tnofest.jpg",
        headerImageAlt: "Smibtno-fest-24",
        client: "Smibtno Fest",
        date: "2024",
        tags: ["Event Graphics"],
        description:
          "Festival located in Amsterdam South-East, organized by SMIB and The New Originals. Features live performances from Hip hop to Jazz and afrobeats, recreational area and catering/food services. With the goal to provide platform for new talent to reach young people in the neighbourhood. \n\n Posters as social content for the festival and development of stage banners for this edition of Smib x TNO fest. Collaborators: Bram Romkes ",
        images: [
          "/images/work/smibtno/lineup.png",
          "/images/work/smibtno/1month.png",
          "/images/work/smibtno/week.png",
          "/images/work/smibtno/3days.png",
          "/images/work/smibtno/afterparty.png",
          "/images/work/smibtno/paneltalk.png",
          "/images/work/smibtno/stage.jpg",
          "/images/work/smibtno/banner1.jpg",
          "/images/work/smibtno/banner2.jpg",

        ],
        mobileLayout:"1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr/ 1fr",
        desktopLayout: "1fr 1fr / 1fr 1fr / 1fr 1fr / 1fr / 1fr / 1fr",
      },
      {
        id: 2,
        title: "The New Originals",
        headerImage: "/images/work/project-thumbnails/tno-2.jpg",
        headerImageAlt: "The-New-Originals",
        client: "The New Originals",
        date: "2024",
        tags: ["Brand Graphics","Product design","Poster design"],
        description:
          "Selected work of various clients during my time at The New Originals. From top to bottom: New Balance Jersey Kit for the Basement Cup 2024. Slipmat design as part of TNO Love Themes pt.2 vinyl release. Posters for collaborative events with TNO. \n\n Collaborators: Bram Romkes, Wessel and Jessey de Nijs. Photography by Brownievisuals",
          images: [
            "/images/work/tno/NB-jersey.jpg",
            "/images/work/tno/nb-jersey-mockup.jpg",
            "/images/work/tno/slipmat.jpg",
            "/images/work/tno/slipmat-store.jpg",
            "/images/work/tno/prophet.jpg",
            "/images/work/tno/dankie.jpg",
            "/images/work/tno/tno-pgltm-mainflyer.jpg",
            "/images/work/tno/tno-pgltm-lineup.jpg",
            "/images/work/tno/jahjah.jpg",
            "/images/work/tno/frediletti.jpg",
            
          ],
        mobileLayout: "1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr / 1fr/ 1fr",
        desktopLayout: "1fr 1fr / 1fr 1fr / 1fr 1fr / 1fr 1fr / 1fr 1fr",
      
      },    
      {
        id: 3,
        title: "Avant Garde Battle",
        headerImage: "/images/work/project-thumbnails/avantgarde.jpg",
        headerImageAlt: "Avant-Garde-Battle",
        client: "Avant Garde Collective",
        date: "2024",
        tags: ["Logo Design","Brand Identity", "Event Graphics"],
        description:
          "Battle event organized by the Avant Garde Collective that took place at the city theater in Haarlem. It features three categories, each with its unique rules and prize money. \n\n The visual language of the event is inspired by the Avant Garde collective's style, blending vintage aesthetics from the early 20th century. This approach reflects both historical influences and modern artistic expression.",
        images: [
          "/images/work/avantgarde/avg-logo.jpg",
          "/images/work/avantgarde/AvantGardeBattle-poster.webp",
          "/images/work/avantgarde/avg-battleguest-1.webp",
          "/images/work/avantgarde/avg-battleguest-2.webp",
          "/images/work/avantgarde/avg-dj.webp",
          "/images/work/avantgarde/avg-lucinda.webp",
          "/images/work/avantgarde/avg-price.webp",
        ],
        mobileLayout: "1fr / 1fr / 1fr / 1fr / 1fr / 1fr",
        desktopLayout: "1fr / 1fr / 1fr 1fr / 1fr 1fr / 1fr / 1fr ",
      },
      {
        id: 4,
        title: "Foundation Hiphop Centre",
        headerImage: "/images/work/project-thumbnails/foundation.jpg",
        headerImageAlt: "Foundation Hiphop Centre afbeelding",
        client: "Foundation Hiphop Centre",
        date: "2023-2024",
        tags: ["Brand Graphics","Poster Design"],
        description:
          "Collection of posters for social media content and printwork for Foundation. Located in South-East of Amsterdam, a cultural centre that provides knowledge and development in various street styles.",
        images: [
          "/images/work/foundation/FD-BC-CLUB-24.jpg",
          "/images/work/foundation/FD-btcmp-24.jpg",
          "/images/work/foundation/ade-talk-24.jpg",
          "/images/work/foundation/HHisErfgoed-IBE.jpg",
          "/images/work/foundation/dreamhampton.jpg",
          "/images/work/foundation/tdhw-battle.jpg",
          "/images/work/foundation/comecorrekt.jpg",
          "/images/work/foundation/FD-OpenDay.jpg",
          "/images/work/foundation/hh-mosey.jpg",
          "/images/work/foundation/house-jasmin.jpg",
        ],
        mobileLayout:
          "1fr / 1fr / 1fr / 1fr/ 1fr / 1fr/ 1fr / 1fr / 1fr / 1fr",
        desktopLayout:
          "1fr 1fr  / 1fr 1fr / 1fr 1fr / 1fr 1fr/ 1fr 1fr",
      },
      // {
      //   id: 5,
      //   title:
      //     "Coke Studio presents: 50 years hiphop tribute powered by Foundation",
      //   headerImage: "/images/work/project-thumbnails/LL-tribute.webp",
      //   headerImageAlt: "Lowlands tribute afbeelding",
      //   client: "Coke studio / Foundation",
      //   date: "2023",
      //   tags: ["Motion Design"],
      //   description:
      //     "August 2023 marks the 50th anniversary of Hiphop, a genre known for its rich cultural history in music. To celebrate this milestone, Coke Studio is presenting a special tribute show titled '50 Years of Hiphop' in collaboration with Lowlands and Foundation Amsterdam Hiphop Academy. \n\n As part of the tribute show, an introductory video showcases a short timeline highlighting the pioneers who have had a significant impact on Hiphop music. This video is a compilation of interviews, music clips, and dynamic text motion.",
      //   images: [
      //     [
      //       "/images/work/LL-tribute/Lowlands-50yrs-hiphop-intro_3.webm",
      //       "/images/work/LL-tribute/LL-tribute.webp",
      //       "/images/work/LL-tribute/Lowlands-50yrs-hiphop-intro_3.mp4",
      //     ],
      //     "/images/work/LL-tribute/73broke.webp",
      //     "/images/work/LL-tribute/electrifying.webp",
      //     "/images/work/LL-tribute/koolherc.webp",
      //     "/images/work/LL-tribute/LL-1.webp",
      //   ],
      //   gridLayout: "100%",
      //   mobileLayout: "1fr / 1fr / 1fr / 1fr",
      //   desktopLayout: "1fr / 1fr / 1fr / 1fr",
      // },
      {
        id: 2,
        title: "Foundation Bootcamp 2023",
        headerImage: "/images/work/project-thumbnails/FD-Bootcamp.webp",
        headerImageAlt: "Foundation Bootcamp afbeelding",
        client: "Foundation Amsterdam Hiphop Academy",
        date: "2023",
        tags: ["Logo Design","Event Graphics"],
        description:
          "Foundation Bootcamp can be summarized as a journey of hard work, growth, challenges, physical and mental exertion and knowledge. Every summer, Foundation Hiphop Academy organizes a 3-week intensive bootcamp that allows dancers to immerse themselves in the elements of street and club culture. The bootcamp offers over 60 workshops in various street styles, as well as lectures, parties and an evaluation program known as the Hawks Method. \n\n The visual language of Foundation Bootcamp is influenced by street and pop art. My inspiration for the design came from hiphop and street magazines, graffiti art, and movie posters. The overall approach aimed to capture the essence of a cityscape, combining elements like an assembly of Avengers.",
        images: [
          "/images/work/FD-Bootcamp/FD-BOOTCAMP2023-FEED.webp",
          "/images/work/FD-Bootcamp/gifbootcamps.gif",
          "/images/work/FD-Bootcamp/arjun.webp",
          "/images/work/FD-Bootcamp/frankwa.webp",
          "/images/work/FD-Bootcamp/jimmyyudat.webp",
          "/images/work/FD-Bootcamp/josephgo.webp",
          "/images/work/FD-Bootcamp/mamson.webp",
          "/images/work/FD-Bootcamp/nedda.webp",
          "/images/work/FD-Bootcamp/suzume.webp",
          "/images/work/FD-Bootcamp/willow.webp",
          "/images/work/FD-Bootcamp/yugson.webp",
          [
            "/images/work/FD-Bootcamp/btcmp-promo.webm",
            "/images/work/FD-Bootcamp/btcmp-promo.webp",
            "/images/work/FD-Bootcamp/btcmp-promo.mp4",
          ],
          [
            "/images/work/FD-Bootcamp/btcmp-teaser_3.webm",
            "/images/work/FD-Bootcamp/btcmp-teaser.webp",
            "/images/work/FD-Bootcamp/btcmp-teaser_3.mp4",
          ],
          "/images/work/FD-Bootcamp/FD-BOOTCAMP-SCHEDULE-W1.webp",
          "/images/work/FD-Bootcamp/FD-BOOTCAMP-SCHEDULE-W2.webp",
          "/images/work/FD-Bootcamp/FD-BOOTCAMP-SCHEDULE-W3.webp",
        ],
        mobileLayout:
          "1fr / 1fr / 1fr 1fr / 1fr 1fr / 1fr 1fr / 1fr 1fr / 1fr / 1fr / 1fr /  1fr / 1fr / 1fr",
        desktopLayout:
          "1.2fr 0.8fr / 1fr 1fr 1fr / 1fr 1fr 1fr / 1fr 1fr 1fr / 1fr 1fr / 1fr / 1fr / 1fr",
      },
      {
        id: 6,
        title: "Yeye: African Diasporic music",
        headerImage: "/images/work/project-thumbnails/YEYE.webp",
        headerImageAlt: "Yeye illustratie",
        client: "Yeye",
        date: "2023",
        tags: ["Event Graphics"],
        description:
          "Yeye is a gathering where people can immerse themselves in the rhythms and melodies that have emerged from the African diaspora, while enjoying delicious food. \n\n For the first event, a looped video backdrop will showcase different music clips with animations featuring Adrinka symbols.",
        images: [
          [
            "/images/work/yeye/landscape.webm",
            "/images/work/yeye/yeye-logo.webp",
            "/images/work/yeye/landscape.mp4",
          ],
          "/images/work/yeye/yeye-logo.webp",
          "/images/work/yeye/yeye-pattern1.webp",
          "/images/work/yeye/yeye-pattern2.webp",
          "/images/work/yeye/yeye-pattern3.webp",
        ],
        mobileLayout: "1fr / 1fr / 1fr / 1fr / 1fr",
        desktopLayout: "1fr / 1fr / 1fr / 1fr / 1fr",
      },
    ],
  }),
  getters: {
    getWork: (state) => state.work,
    getWorkItem: (state) => (title: string) =>
      state.work.find(
        (workItem) => workItem.title.toLowerCase() === title.toLowerCase()
      ),
  },
  actions: {},
});
